### ISSUE TITLE
Add features short descriptions  

### ISSUE THREAD

**Issue by suraiya-akter** [Abir-Tx/aiub-discobot.web#6]
Add main features so that new users can get to know about the bot.

**Comment by Abir-Tx** [comment]
Okay will start working on it soon

**Comment by suraiya-akter** [comment]
Traffic-signal-Control-system (SURAIYA AKTER).mp4
<https://drive.google.com/file/d/1Uqr-k7bb7lHvX2IqzwzTuiho8LbKc4gb/view?usp=drive_web>

**Comment by Abir-Tx** [comment]
Fixed at 2a1794950636f148d28017d0581a9ea74e272f04

**Comment by suraiya-akter** [comment]
Ata ki kortm?

**Comment by Abir-Tx** [comment]
Wow ! Tumi notification check koro !

Anyway kisu korte hobena tomar, ami issue ta resolve korlam to tai r ki. Jun 19, 2022 e ekta suggestion disila ota aj korlam tai xD

**Comment by suraiya-akter** [comment]
Ha.
Ok ok
